version: 1.0.{build}
environment:
  PlatformToolset: v141
branches:
  only:
  - master
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- Win32
- x64
build:
  project: ds.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: 'C:\projects\ds\dsUT\./../output/windows/vs/v141/%PLATFORM%/Debug/dsUT.exe --gtest_output="xml:C:\projects\ds\dsUT\./../output/windows/vs/v141/%PLATFORM%/Debug/dsUT.xml'