version: 1.0.{build}
environment:
  PlatformToolset: v141
branches:
  only:
  - master
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- Win32
- x64
build:
  project: ds.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: '%APPVEYOR_BUILD_FOLDER%\dsUT\./../output/windows/vs/%PlatformToolset%/%PLATFORM%/%CONFIGURATION%/dsUT.exe --gtest_output="xml:.\dsUT.xml'
on_finish:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\dsUT.xml))